import { App } from "./App";
import "./globals.css";

export const metadata = {
  title: "Pindie",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body>
      <App>{children}</App>
      </body>
    </html>
  );
}
